"""Check that a SWAN image runs workspaces generated by rompy-swan.

Generates two short models from the test data and runs them in the image:

- stationary: GEBCO bathymetry and a constant parametric boundary;
- nonstationary: GEBCO bathymetry, ERA5 winds and spectral boundaries from WW3,
  run serially and with MPI.

Each run must finish and write its map and spectra output as NetCDF.

Usage: python docker/test_image.py <image>
"""

import subprocess
import sys
import tempfile
from pathlib import Path

from rompy.core.source import SourceFile
from rompy.core.time import TimeRange
from rompy.model import ModelRun

from rompy_swan.boundary import Boundnest1
from rompy_swan.components.boundary import BOUNDSPEC
from rompy_swan.components.cgrid import REGULAR
from rompy_swan.components.group import LOCKUP, OUTPUT, PHYSICS, STARTUP
from rompy_swan.components.lockup import COMPUTE, COMPUTE_NONSTAT
from rompy_swan.components.output import BLOCK, POINTS, SPECOUT
from rompy_swan.components.physics import GEN3, OFF, OFFS
from rompy_swan.components.startup import COORDINATES, MODE, SET
from rompy_swan.config import SwanConfig
from rompy_swan.data import SwanDataGrid
from rompy_swan.grid import SwanGrid
from rompy_swan.interface import BoundaryInterface, DataInterface
from rompy_swan.subcomponents.spectrum import SPECTRUM

TESTS = Path(__file__).resolve().parents[1] / "tests"
DATA = TESTS / "data"
NETCDF_MAGIC = (b"CDF", b"\x89HDF")

GRID = SwanGrid(x0=110.0, y0=-35.0, rot=0.0, dx=0.5, dy=0.5, nx=13, ny=9)


def config(mode, inputs, boundary, physics, compute):
    """A small spherical model off Western Australia."""
    return SwanConfig(
        startup=STARTUP(
            set=SET(direction_convention="nautical"),
            mode=MODE(kind=mode),
            coordinates=COORDINATES(kind={"model_type": "spherical"}),
        ),
        cgrid=REGULAR(
            grid=GRID.component, spectrum=SPECTRUM(mdc=24, flow=0.04, fhigh=0.5)
        ),
        inpgrid=DataInterface(
            bottom=SwanDataGrid(
                var="bottom",
                source=SourceFile(uri=DATA / "gebco-1deg.nc"),
                z1="elevation",
                fac=-1.0,
                coords={"x": "lon", "y": "lat"},
            ),
            input=inputs,
        ),
        boundary=boundary,
        physics=physics,
        output=OUTPUT(
            points=POINTS(sname="pts", xp=[112.0], yp=[-33.0]),
            block=BLOCK(sname="COMPGRID", fname="grid.nc", output=["hsign", "dir"]),
            specout=SPECOUT(sname="pts", fname="spec.nc"),
        ),
        lockup=LOCKUP(compute=compute),
    )


WIND = SwanDataGrid(
    var="wind",
    source=SourceFile(uri=DATA / "era5-20230101.nc"),
    z1="u10",
    z2="v10",
    coords={"x": "longitude", "y": "latitude"},
    filter={"sort": {"coords": ["latitude"]}},
    buffer=5.0,  # the test data is on a 5 degree grid
)
CASES = {
    # No wind, so quadruplets are switched off as SWAN requires
    "stationary": config(
        mode="stationary",
        inputs=[],
        boundary=BOUNDSPEC(
            shapespec={"shape": {"model_type": "jonswap"}, "dspr_type": "degrees"},
            location={"model_type": "side", "side": "west", "direction": "ccw"},
            data={"model_type": "constantpar", "hs": 2.0, "per": 12.0, "dir": 250.0},
        ),
        physics=PHYSICS(gen=GEN3(), deactivate=OFFS(offs=[OFF(physics="quadrupl")])),
        compute=COMPUTE(),
    ),
    "nonstationary": config(
        mode="nonstationary",
        inputs=[WIND],
        boundary=BoundaryInterface(
            kind=Boundnest1(
                id="ww3",
                source=SourceFile(uri=DATA / "aus-20230101.nc"),
                sel_method="idw",
                sel_method_kwargs={"tolerance": 4.0},
            )
        ),
        physics=PHYSICS(gen=GEN3()),
        compute=COMPUTE_NONSTAT(),
    ),
}
COMMANDS = {
    "stationary": ["swan.exe"],
    "nonstationary": ["swan.exe"],
    "nonstationary-mpi": [
        "mpirun",
        "--allow-run-as-root",
        "--oversubscribe",
        "-n",
        "2",
        "swan.exe",
    ],
}


def is_netcdf(path: Path) -> bool:
    return path.exists() and path.read_bytes()[:4].startswith(NETCDF_MAGIC)


def main(image: str) -> int:
    # Importing the test configuration downloads the test data if it is missing
    sys.path.insert(0, str(TESTS))
    import conftest  # noqa: F401

    period = TimeRange(start="2023-01-01T00", end="2023-01-01T06", interval="1h")
    failed = []
    with tempfile.TemporaryDirectory() as tmp:
        for name, command in COMMANDS.items():
            case = name.split("-")[0]
            run = ModelRun(
                run_id=name, period=period, output_dir=tmp, config=CASES[case]
            )
            workspace = Path(run()).resolve()
            result = subprocess.run(
                ["docker", "run", "--rm", "-v", f"{workspace}:/data", image, *command],
                capture_output=True,
                text=True,
            )
            outputs = [workspace / "grid.nc", workspace / "spec.nc"]
            ok = result.returncode == 0 and all(is_netcdf(f) for f in outputs)
            print(f"{name}: {'OK' if ok else 'FAILED'}")
            if not ok:
                print(result.stdout[-2000:], result.stderr[-2000:])
                for prt in sorted(workspace.glob("PRINT*")):
                    errors = [ln for ln in prt.read_text().splitlines() if "rror" in ln]
                    print(prt.name, *errors[:10], sep="\n  ")
                failed.append(name)
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1]))
